name: e-id

on:
  push:
    branches:
      - master

jobs:
  deploy-development:
    name: Deploy development
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Copy file
        run: rsync -azh --exclude={.git,.github,.env,dist,node_modules,docker,data} --delete ./ ~/e-id/backend
      - name: w
        run: w
      - name: Run build
        run: |
          cd ~/e-id/backend
          docker compose up -d --build